### PR TITLE
 Update appveyor-ci config

### PR DESCRIPTION
**Pull request by liuhaoyang**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this making ci running in real way?

**Comment by wu-sheng** [comment]
build. cake is a very new to me. Never use this in Java before.😂😂

**Comment by liuhaoyang** [comment]
@wu-sheng  [Cake (C# Make)](https://github.com/cake-build/cake) is a cross platform build automation system for dotnet. I use cake to auto-generate version numbers, such as `SkyWalking.NetworkProtocol.1.0.0-preview-35646926`

**Comment by liuhaoyang** [comment]
It also runs test and pack.

**Pull request merged**
