### PR TITLE
Replace physical proto folder by git submodule link

### PR DESCRIPTION
**Pull request by wu-sheng**
By linking folder to https://github.com/apache/incubator-skywalking-data-collect-protocol , we can share the unique proto definition files. If you are not familiar with `git submodule`, you should learn, because, you need to udpate the link by `submodule update` command, when the protocol updated for some reasons.

### CODE REVIEW

**Comment by liuhaoyang** [comment]
protos need to add `package SkyWalking.NetworkProtocol;` to generate namespace for C# code. Just like [ApplicationRegisterService.proto#L8](https://github.com/OpenSkywalking/skywalking-csharp/blob/master/protos/ApplicationRegisterService.proto#L8)

**Comment by liuhaoyang** [comment]
Yes. I have used `git submodule` to update the links. Then run `generate_protos.bat` to re-generate the C # files , and run `dotnet build` to re-build the project ,an error occurred : 
```
DiscoveryServiceGrpc.cs(13,12): error CS1001: Identifier expected [D:\skywalking-csharp\src\SkyWalking.NetworkProtocol\SkyWalking.NetworkProtocol.csproj]
```
So we  need to add `package SkyWalking.NetworkProtocol;` into proto definition files to fix this issue . e.g.

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.apache.skywalking.apm.network.proto";

import "KeyWithIntegerValue.proto";

package SkyWalking.NetworkProtocol;

...
```

**Comment by wu-sheng** [comment]
Get your point. But by following grpc offical examples: https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto#L22 ,  I prefer the package name stays in lower case. Such as `skywalking.network.protocol`.

What do you think?

**Comment by wu-sheng** [comment]
And I check the generated source codes: https://github.com/grpc/grpc/blob/master/examples/csharp/helloworld-from-cli/Greeter/Helloworld.cs#L10

Look like the first letter of each package name will be upper.

**Comment by liuhaoyang** [comment]
The better way is explicitly provide an option csharp_namespace in proto files.  https://developers.google.com/protocol-buffers/docs/proto3#packages

**Pull request merged**
